[break changes] add maxReadBatches and endRecordId to ReadShardStreamRequest
hstreamdb/protocol pull request #81
Opened 2023-07-03 06:09 UTC by YangKian

2023-07-03 06:41 UTC, daleiz requested changes

2023-07-03 06:41 UTC, daleiz commented on hstream.proto
> +  RecordId endRecordId = 5;
.

2023-07-04 02:04 UTC, 4eUeP commented on hstream.proto
> +  ShardOffset until = 5;
```suggestion
  ShardOffset from = 3;
  ShardOffset until = 4;
  // Total number of batches reader read at most
  uint64 maxReadBatches = 5;
```

2023-07-04 02:04 UTC, 4eUeP approved these changes

2023-07-04 02:11 UTC, daleiz approved these changes

2023-07-04 02:11 UTC, merged